import json

def build_03():
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 3: Targeted Voice Artifact Synthesis (GGUF)\n",
            "This notebook uses the highly-optimized Python and `llama_cpp` integration to synthesize voice artifacts using the Svara-TTS `Q3_K_S.gguf` model."
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "!pip install -q llama-cpp-python onnxruntime soundfile huggingface_hub numpy\n",
            "\n",
            "from huggingface_hub import hf_hub_download\n",
            "import os\n",
            "\n",
            "print(\"Downloading SNAC ONNX Decoder...\")\n",
            "SNAC_DECODER = hf_hub_download(repo_id=\"hubertsiuzdak/snac_24khz-ONNX\", filename=\"onnx/decoder_model.onnx\")\n",
            "\n",
            "print(\"Downloading Svara TTS Q3_K_S GGUF...\")\n",
            "MODEL_PATH = hf_hub_download(repo_id=\"mradermacher/svara-tts-v1-GGUF\", filename=\"svara-tts-v1.Q3_K_S.gguf\")\n",
            "\n",
            "print(f\"Decoder path: {SNAC_DECODER}\")\n",
            "print(f\"Model path: {MODEL_PATH}\")\n"
        ]
    })

    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import json, os, time, re\n",
            "from pathlib import Path\n",
            "import numpy as np\n",
            "import onnxruntime as ort\n",
            "import soundfile as sf\n",
            "from llama_cpp import Llama\n",
            "\n",
            "OUTPUT_ROOT = Path(\"/kaggle/working/idp_curriculum_generation\")\n",
            "PACK_ROOT = OUTPUT_ROOT / \"generated_pack\"\n",
            "VOICE_ROOT = PACK_ROOT / \"voice\"\n",
            "STRUCTURED_ROOT = OUTPUT_ROOT / \"structured_chapters\"\n",
            "\n",
            "for d in [\"section_summaries\", \"concepts\", \"glossary\", \"faqs\", \"doubts\", \"flashcards\"]:\n",
            "    (VOICE_ROOT / d).mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "SAMPLE_RATE = 24000\n",
            "PAUSE_SAMPLES = int(1.5 * SAMPLE_RATE)\n",
            "\n",
            "def snac_codes(tokens, input_len):\n",
            "    generated = [int(x) for x in tokens[input_len:]]\n",
            "    start = generated.index(128257) + 1 if 128257 in generated else 0\n",
            "    audio = []\n",
            "    band_pos = 0\n",
            "    for token in generated[start:]:\n",
            "        if token == 128258: break\n",
            "        if token < 128266 or token >= 156938: continue\n",
            "        band = band_pos % 7\n",
            "        code = token - 128266 - band * 4096\n",
            "        if 0 <= code < 4096:\n",
            "            audio.append((band, code))\n",
            "            band_pos += 1\n",
            "    frames = len(audio) // 7\n",
            "    level0, level1, level2 = [], [], []\n",
            "    for i in range(frames):\n",
            "        codes = [c for _, c in audio[i * 7 : i * 7 + 7]]\n",
            "        level0.append(codes[0])\n",
            "        level1.extend([codes[1], codes[4]])\n",
            "        level2.extend([codes[2], codes[3], codes[5], codes[6]])\n",
            "    return {\n",
            "        \"frames\": frames,\n",
            "        \"level0\": np.asarray([level0], dtype=np.int64),\n",
            "        \"level1\": np.asarray([level1], dtype=np.int64),\n",
            "        \"level2\": np.asarray([level2], dtype=np.int64),\n",
            "    }\n",
            "\n",
            "def decode_snac(session, codes):\n",
            "    if codes[\"frames\"] < 1: return np.array([], dtype=np.float32)\n",
            "    out = session.run(None, {\n",
            "        \"audio_codes.0\": codes[\"level0\"],\n",
            "        \"audio_codes.1\": codes[\"level1\"],\n",
            "        \"audio_codes.2\": codes[\"level2\"],\n",
            "    })\n",
            "    return np.asarray(out[0]).reshape(-1)\n",
            "\n",
            "def chunk_text(text, max_words=20):\n",
            "    if not text: return []\n",
            "    sentences = [s.strip() for s in re.split(r'(?<=[.!?]) +', text.replace('\\n', ' ')) if s.strip()]\n",
            "    if not sentences: sentences = [text]\n",
            "    chunks = []\n",
            "    curr = \"\"\n",
            "    for s in sentences:\n",
            "        if len((curr + \" \" + s).split()) > max_words and curr:\n",
            "            chunks.append(curr.strip())\n",
            "            curr = s\n",
            "        else:\n",
            "            curr += \" \" + s\n",
            "    if curr.strip(): chunks.append(curr.strip())\n",
            "    return chunks\n",
            "\n",
            "report = {\"total_files\": 0, \"start_time\": time.time(), \"errors\": [], \"categories\": {}}\n",
            "manifest = {\"chapter_id\": \"unknown\", \"summary\": \"\", \"objectives\": \"\", \"full_narration\": \"\", \"sections\": [], \"concepts\": [], \"glossary\": [], \"faqs\": [], \"doubts\": [], \"flashcards\": []}\n",
            "\n",
            "print(\"Loading models...\")\n",
            "llm = Llama(model_path=MODEL_PATH, n_ctx=4096, n_threads=8, n_gpu_layers=0, logits_all=False, verbose=False)\n",
            "decoder = ort.InferenceSession(SNAC_DECODER, providers=[\"CPUExecutionProvider\"])\n",
            "\n",
            "def synthesize_wav(text_chunks, output_path, category, insert_pause=False):\n",
            "    if output_path.exists(): return str(output_path.relative_to(VOICE_ROOT))\n",
            "    \n",
            "    print(f\"Synthesizing [{category}]: {output_path.name}\")\n",
            "    combined_samples = []\n",
            "    for i, chunk in enumerate(text_chunks):\n",
            "        if not chunk: continue\n",
            "        try:\n",
            "            body = llm.tokenize(f\"English (Indian) (Female): {chunk}\".encode(\"utf-8\"), add_bos=False, special=True)\n",
            "            ids = [128259, llm.token_bos()] + list(body) + [128009, 128260]\n",
            "            \n",
            "            generated = []\n",
            "            for token in llm.generate(ids, temp=0.6, top_k=40, top_p=0.9, repeat_penalty=1.0, reset=True):\n",
            "                generated.append(int(token))\n",
            "                if int(token) == 128258 or len(generated) >= 200: break\n",
            "                    \n",
            "            codes = snac_codes(ids + generated, len(ids))\n",
            "            audio = decode_snac(decoder, codes)\n",
            "            if len(audio) > 0: combined_samples.append(audio)\n",
            "            \n",
            "            if insert_pause and i < len(text_chunks) - 1:\n",
            "                combined_samples.append(np.zeros(PAUSE_SAMPLES, dtype=np.float32))\n",
            "                \n",
            "        except Exception as e:\n",
            "            report[\"errors\"].append(f\"Error chunk '{chunk}': {e}\")\n",
            "            \n",
            "    if combined_samples:\n",
            "        final_audio = np.concatenate(combined_samples)\n",
            "        sf.write(output_path, final_audio, SAMPLE_RATE)\n",
            "        report[\"total_files\"] += 1\n",
            "        report[\"categories\"][category] = report[\"categories\"].get(category, 0) + 1\n",
            "        return str(output_path.relative_to(VOICE_ROOT))\n",
            "    \n",
            "    report[\"errors\"].append(f\"Failed to generate: {output_path.name}\")\n",
            "    return None\n",
            "\n",
            "def clean_slug(text):\n",
            "    return re.sub(r'[^a-z0-9]+', '_', str(text).lower()).strip('_')[:50]\n",
            "\n",
            "def read_json(fname):\n",
            "    p = PACK_ROOT / fname\n",
            "    return json.loads(p.read_text(\"utf-8\")) if p.exists() else []\n",
            "\n",
            "# 1. SECTION SUMMARIES\n",
            "all_summaries = []\n",
            "for s in read_json(\"summary.json\"):\n",
            "    if s.get(\"chapter_id\"): manifest[\"chapter_id\"] = s[\"chapter_id\"]\n",
            "    txt = s.get(\"payload\", {}).get(\"summary_short\", \"\")\n",
            "    if txt:\n",
            "        all_summaries.append(txt)\n",
            "        p = synthesize_wav(chunk_text(txt), VOICE_ROOT / \"section_summaries\" / f\"{s.get('section_id')}.wav\", \"section_summaries\")\n",
            "        if p: manifest[\"sections\"].append(p)\n",
            "\n",
            "if all_summaries:\n",
            "    p = synthesize_wav(chunk_text(\" \".join(all_summaries)), VOICE_ROOT / \"chapter_summary.wav\", \"section_summaries\")\n",
            "    if p: manifest[\"summary\"] = p\n",
            "\n",
            "# 2. OBJECTIVES\n",
            "obj_texts = []\n",
            "for o in read_json(\"learning_objectives.json\"):\n",
            "    for i in o.get(\"payload\", {}).get(\"learning_objectives\", []):\n",
            "        obj_texts.append(i.get(\"objective\", \"\"))\n",
            "if obj_texts:\n",
            "    p = synthesize_wav(chunk_text(\" \".join(obj_texts)), VOICE_ROOT / \"learning_objectives.wav\", \"section_summaries\")\n",
            "    if p: manifest[\"objectives\"] = p\n",
            "\n",
            "# 3. CONCEPTS\n",
            "for s in read_json(\"concepts.json\"):\n",
            "    for c in s.get(\"payload\", {}).get(\"concepts\", []):\n",
            "        if c.get(\"name\"):\n",
            "            p = synthesize_wav(chunk_text(c[\"name\"]), VOICE_ROOT / \"concepts\" / f\"{clean_slug(c['name'])}.wav\", \"concepts\")\n",
            "            if p: manifest[\"concepts\"].append(p)\n",
            "\n",
            "# 4. GLOSSARY\n",
            "for s in read_json(\"glossary.json\"):\n",
            "    for g in s.get(\"payload\", {}).get(\"glossary\", []):\n",
            "        if g.get(\"term\"):\n",
            "            txt = f\"{g['term']}. {g.get('definition', '')}\"\n",
            "            p = synthesize_wav(chunk_text(txt), VOICE_ROOT / \"glossary\" / f\"{clean_slug(g['term'])}.wav\", \"glossary\")\n",
            "            if p: manifest[\"glossary\"].append(p)\n",
            "\n",
            "# 5. FAQS\n",
            "idx = 1\n",
            "for s in read_json(\"faqs.json\"):\n",
            "    for f in s.get(\"payload\", {}).get(\"items\", []):\n",
            "        txt = f\"{f.get('question', '')} {f.get('answer', '')}\"\n",
            "        p = synthesize_wav(chunk_text(txt), VOICE_ROOT / \"faqs\" / f\"faq_{idx:03d}.wav\", \"faqs\")\n",
            "        if p: manifest[\"faqs\"].append(p)\n",
            "        idx += 1\n",
            "\n",
            "# 6. DOUBTS\n",
            "idx = 1\n",
            "for s in read_json(\"common_doubts.json\"):\n",
            "    for d in s.get(\"payload\", {}).get(\"items\", []):\n",
            "        txt = f\"{d.get('doubt', '')} {d.get('explanation', '')}\"\n",
            "        p = synthesize_wav(chunk_text(txt), VOICE_ROOT / \"doubts\" / f\"doubt_{idx:03d}.wav\", \"doubts\")\n",
            "        if p: manifest[\"doubts\"].append(p)\n",
            "        idx += 1\n",
            "\n",
            "# 7. FLASHCARDS\n",
            "idx = 1\n",
            "for s in read_json(\"flashcards.json\"):\n",
            "    for f in s.get(\"payload\", {}).get(\"items\", []):\n",
            "        if f.get(\"front\") and f.get(\"back\"):\n",
            "            parts = chunk_text(f[\"front\"]) + chunk_text(f[\"back\"])\n",
            "            p = synthesize_wav(parts, VOICE_ROOT / \"flashcards\" / f\"flashcard_{idx:03d}.wav\", \"flashcards\", insert_pause=True)\n",
            "            if p: manifest[\"flashcards\"].append(p)\n",
            "            idx += 1\n",
            "\n",
            "# 8. FULL NARRATION\n",
            "full_text = \"\"\n",
            "for p in STRUCTURED_ROOT.rglob(\"structured_chapter.json\"):\n",
            "    try:\n",
            "        j = json.loads(p.read_text(\"utf-8\"))\n",
            "        for sec in j.get(\"sections\", []):\n",
            "            full_text += sec.get(\"content\", \"\") + \". \"\n",
            "    except: pass\n",
            "if full_text.strip():\n",
            "    p = synthesize_wav(chunk_text(full_text, 30), VOICE_ROOT / \"full_chapter.wav\", \"full_narration\")\n",
            "    if p: manifest[\"full_narration\"] = p\n",
            "\n",
            "# Wrap up\n",
            "(VOICE_ROOT / \"voice_manifest.json\").write_text(json.dumps(manifest, indent=2))\n",
            "report[\"total_time_seconds\"] = round(time.time() - report[\"start_time\"])\n",
            "(VOICE_ROOT / \"voice_generation_report.json\").write_text(json.dumps(report, indent=2))\n",
            "print(\"\\n\\nVoice generation complete! Report:\")\n",
            "print(json.dumps(report, indent=2))\n"
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import zipfile\n",
            "zip_path = OUTPUT_ROOT / \"generated_pack_with_voice.zip\"\n",
            "with zipfile.ZipFile(zip_path, \"w\", zipfile.ZIP_DEFLATED) as archive:\n",
            "    # Add all JSON artifacts\n",
            "    for file_path in PACK_ROOT.rglob(\"*.json\"):\n",
            "        archive.write(file_path, arcname=str(file_path.relative_to(PACK_ROOT.parent)))\n",
            "    # Add all Audio artifacts and manifest\n",
            "    for file_path in VOICE_ROOT.rglob(\"*.wav\"):\n",
            "        archive.write(file_path, arcname=str(file_path.relative_to(PACK_ROOT.parent)))\n",
            "    voice_manifest = VOICE_ROOT / \"voice_manifest.json\"\n",
            "    if voice_manifest.exists():\n",
            "        archive.write(voice_manifest, arcname=str(voice_manifest.relative_to(PACK_ROOT.parent)))\n",
            "    voice_report = VOICE_ROOT / \"voice_generation_report.json\"\n",
            "    if voice_report.exists():\n",
            "        archive.write(voice_report, arcname=str(voice_report.relative_to(PACK_ROOT.parent)))\n",
            "print(\"Process complete. Final zip saved to\", zip_path)\n"
        ]
    })
    
    with open('/home/akash/Desktop/PIHUB/03_VOICE_GENERATION.ipynb', 'w') as f:
        json.dump({"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}, f, indent=2)

build_03()
