import json

def build_02():
    cells = []
    
    # 00_MARKDOWN
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 2: LLM Artifact Generation\n",
            "\n",
            "This notebook runs Gemma to generate educational artifacts, including specifically targeted `faqs` and `common_doubts`.\n"
        ]
    })
    
    # 01_CONFIG
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "CONFIG = {\n",
            "    \"output_root\": \"/kaggle/working/idp_curriculum_generation\",\n",
            "    \"content_model_repo\": \"lmstudio-community/gemma-4-12B-it-GGUF\",\n",
            "    \"content_model_file\": \"gemma-4-12B-it-Q4_K_M.gguf\",\n",
            "\n",
            "    # Generation controls.\n",
            "    \"generate_concepts\": True,\n",
            "    \"generate_learning_objectives\": True,\n",
            "    \"generate_glossary\": True,\n",
            "    \"generate_summary\": True,\n",
            "    \"generate_detailed_explanation\": True,\n",
            "    \"generate_misconceptions\": True,\n",
            "    \"generate_mcq_quiz\": True,\n",
            "    \"generate_short_answer\": True,\n",
            "    \"generate_flashcards\": True,\n",
            "    \"generate_concept_relationships\": True,\n",
            "    \"generate_image_captions\": True,\n",
            "    \"generate_investigations\": True,\n",
            "    \"generate_teacher_notes\": True,\n",
            "    \"generate_prerequisites\": True,\n",
            "    \"generate_difficulty_analysis\": True,\n",
            "    \"generate_faqs\": True,\n",
            "    \"generate_common_doubts\": True,\n",
            "\n",
            "    # llama.cpp generation settings.\n",
            "    \"temperature\": 0.2,\n",
            "    \"top_p\": 0.9,\n",
            "    \"max_tokens\": 900,\n",
            "    \"context_size\": 8192,\n",
            "    \"n_gpu_layers\": -1,\n",
            "    \"n_threads\": 4,\n",
            "    \"max_retries\": 3,\n",
            "    \"resume\": True,\n",
            "    \"artifact_zip_name\": \"generated_pack.zip\"\n",
            "}\n"
        ]
    })
    
    # 02_ENV
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "!pip -q install llama-cpp-python jsonschema pandas tqdm huggingface_hub\n",
            "\n",
            "import json, logging, os, re, time, hashlib, zipfile\n",
            "from dataclasses import dataclass, field\n",
            "from pathlib import Path\n",
            "from typing import Any, Dict, List\n",
            "from tqdm.auto import tqdm\n",
            "from jsonschema import validate as jsonschema_validate\n",
            "\n",
            "OUTPUT_ROOT = Path(CONFIG[\"output_root\"])\n",
            "CACHE_ROOT = OUTPUT_ROOT / \"cache\"\n",
            "STRUCTURED_ROOT = OUTPUT_ROOT / \"structured_chapters\"\n",
            "PACK_ROOT = OUTPUT_ROOT / \"generated_pack\"\n",
            "\n",
            "for path in [CACHE_ROOT, PACK_ROOT]:\n",
            "    path.mkdir(parents=True, exist_ok=True)\n"
        ]
    })
    
    # 03_LOAD_CHAPTERS
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "@dataclass\n",
            "class FigureData:\n",
            "    figure_id: str\n",
            "    caption: str = \"\"\n",
            "    image_path: str = \"\"\n",
            "\n",
            "@dataclass\n",
            "class SectionData:\n",
            "    section_id: str\n",
            "    title: str\n",
            "    content: str\n",
            "    tables: List[Dict[str, Any]] = field(default_factory=list)\n",
            "    figures: List[FigureData] = field(default_factory=list)\n",
            "    equations: List[str] = field(default_factory=list)\n",
            "\n",
            "@dataclass\n",
            "class ChapterData:\n",
            "    document_id: str\n",
            "    chapter_title: str\n",
            "    grade: str\n",
            "    subject: str\n",
            "    sections: List[SectionData]\n",
            "\n",
            "CHAPTERS = []\n",
            "for p in STRUCTURED_ROOT.rglob(\"structured_chapter.json\"):\n",
            "    raw = json.loads(p.read_text(encoding=\"utf-8\"))\n",
            "    sections = []\n",
            "    for s in raw.get(\"sections\", []):\n",
            "        figs = [FigureData(**f) for f in s.get(\"figures\", [])]\n",
            "        sections.append(SectionData(s[\"section_id\"], s[\"title\"], s[\"content\"], s.get(\"tables\", []), figs, s.get(\"equations\", [])))\n",
            "    CHAPTERS.append(ChapterData(raw[\"document_id\"], raw[\"chapter_title\"], raw[\"grade\"], raw[\"subject\"], sections))\n",
            "\n",
            "print(f\"Loaded {len(CHAPTERS)} structured chapters.\")\n"
        ]
    })
    
    # 04_MODEL
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from llama_cpp import Llama\n",
            "\n",
            "try:\n",
            "    CONTENT_LLM = Llama.from_pretrained(\n",
            "        repo_id=CONFIG[\"content_model_repo\"],\n",
            "        filename=CONFIG[\"content_model_file\"],\n",
            "        n_ctx=int(CONFIG[\"context_size\"]),\n",
            "        n_gpu_layers=int(CONFIG[\"n_gpu_layers\"]),\n",
            "        n_threads=int(CONFIG[\"n_threads\"]),\n",
            "        verbose=False,\n",
            "    )\n",
            "    print(\"Model loaded successfully!\")\n",
            "except Exception as e:\n",
            "    print(f\"Failed to load model: {e}\")\n"
        ]
    })

    # 05_GENERATION_SCHEMA_LOGIC
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "ARTIFACT_SPECS: Dict[str, Dict[str, Any]] = {\n",
            "    \"concepts\": {\"enabled\": \"generate_concepts\", \"file\": \"concepts.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"concept\", \"evidence\"], \"properties\": {\"concept\": {\"type\": \"string\"}, \"evidence\": {\"type\": \"string\"}, \"difficulty\": {\"type\": \"string\"}}}}}}},\n",
            "    \"learning_objectives\": {\"enabled\": \"generate_learning_objectives\", \"file\": \"learning_objectives.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"objective\"], \"properties\": {\"objective\": {\"type\": \"string\"}}}}}}},\n",
            "    \"glossary\": {\"enabled\": \"generate_glossary\", \"file\": \"glossary.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"term\", \"definition\"], \"properties\": {\"term\": {\"type\": \"string\"}, \"definition\": {\"type\": \"string\"}}}}}}},\n",
            "    \"summary\": {\"enabled\": \"generate_summary\", \"file\": \"summary.json\", \"schema\": {\"type\": \"object\", \"required\": [\"title\", \"summary\", \"key_points\"], \"properties\": {\"title\": {\"type\": \"string\"}, \"summary\": {\"type\": \"string\"}, \"key_points\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"important_facts\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}},\n",
            "    \"detailed_explanation\": {\"enabled\": \"generate_detailed_explanation\", \"file\": \"detailed_explanation.json\", \"schema\": {\"type\": \"object\", \"required\": [\"explanation\"], \"properties\": {\"explanation\": {\"type\": \"string\"}, \"teaching_steps\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}},\n",
            "    \"misconceptions\": {\"enabled\": \"generate_misconceptions\", \"file\": \"misconceptions.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"misconception\", \"correction\"], \"properties\": {\"misconception\": {\"type\": \"string\"}, \"correction\": {\"type\": \"string\"}}}}}}},\n",
            "    \"mcq_quiz\": {\"enabled\": \"generate_mcq_quiz\", \"file\": \"mcq_quiz.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"question\", \"options\", \"answer\", \"explanation\", \"difficulty\"], \"properties\": {\"question\": {\"type\": \"string\"}, \"options\": {\"type\": \"array\", \"minItems\": 4, \"maxItems\": 4, \"items\": {\"type\": \"string\"}}, \"answer\": {\"type\": \"string\"}, \"explanation\": {\"type\": \"string\"}, \"difficulty\": {\"type\": \"string\"}}}}}}},\n",
            "    \"short_answer_questions\": {\"enabled\": \"generate_short_answer\", \"file\": \"short_answer_questions.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"question\", \"answer\", \"rubric\"], \"properties\": {\"question\": {\"type\": \"string\"}, \"answer\": {\"type\": \"string\"}, \"rubric\": {\"type\": \"string\"}}}}}}},\n",
            "    \"flashcards\": {\"enabled\": \"generate_flashcards\", \"file\": \"flashcards.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"question\", \"answer\", \"difficulty\"], \"properties\": {\"question\": {\"type\": \"string\"}, \"answer\": {\"type\": \"string\"}, \"difficulty\": {\"type\": \"string\"}}}}}}},\n",
            "    \"concept_relationships\": {\"enabled\": \"generate_concept_relationships\", \"file\": \"concept_relationships.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"source\", \"target\", \"relationship\"], \"properties\": {\"source\": {\"type\": \"string\"}, \"target\": {\"type\": \"string\"}, \"relationship\": {\"type\": \"string\"}}}}}}},\n",
            "    \"image_captions\": {\"enabled\": \"generate_image_captions\", \"file\": \"image_captions.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"figure_id\", \"caption\", \"evidence\"], \"properties\": {\"figure_id\": {\"type\": \"string\"}, \"caption\": {\"type\": \"string\"}, \"evidence\": {\"type\": \"string\"}, \"confidence\": {\"type\": \"string\"}}}}}}},\n",
            "    \"investigations\": {\"enabled\": \"generate_investigations\", \"file\": \"investigations.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"title\", \"hypothesis\", \"variables\", \"observations\"], \"properties\": {\"title\": {\"type\": \"string\"}, \"hypothesis\": {\"type\": \"string\"}, \"variables\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"observations\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"teacher_notes\": {\"enabled\": \"generate_teacher_notes\", \"file\": \"teacher_notes.json\", \"schema\": {\"type\": \"object\", \"required\": [\"notes\"], \"properties\": {\"notes\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"classroom_tips\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}},\n",
            "    \"prerequisites\": {\"enabled\": \"generate_prerequisites\", \"file\": \"prerequisites.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"concept\", \"prerequisite\"], \"properties\": {\"concept\": {\"type\": \"string\"}, \"prerequisite\": {\"type\": \"string\"}}}}}}},\n",
            "    \"difficulty_analysis\": {\"enabled\": \"generate_difficulty_analysis\", \"file\": \"difficulty_analysis.json\", \"schema\": {\"type\": \"object\", \"required\": [\"difficulty\", \"reasons\"], \"properties\": {\"difficulty\": {\"type\": \"string\"}, \"reasons\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"estimated_grade_fit\": {\"type\": \"string\"}}}},\n",
            "    \"faqs\": {\"enabled\": \"generate_faqs\", \"file\": \"faqs.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"question\", \"answer\"], \"properties\": {\"question\": {\"type\": \"string\"}, \"answer\": {\"type\": \"string\"}}}}}}},\n",
            "    \"common_doubts\": {\"enabled\": \"generate_common_doubts\", \"file\": \"common_doubts.json\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"doubt\", \"clarification\"], \"properties\": {\"doubt\": {\"type\": \"string\"}, \"clarification\": {\"type\": \"string\"}}}}}}}\n",
            "}\n",
            "\n",
            "def strip_markdown_fences(text: str) -> str:\n",
            "    text = (text or \"\").strip()\n",
            "    if text.startswith(\"```\"):\n",
            "        text = re.sub(r\"^```[a-zA-Z0-9_-]*\\s*\", \"\", text).strip()\n",
            "        text = re.sub(r\"\\s*```$\", \"\", text).strip()\n",
            "    return text\n",
            "\n",
            "def extract_balanced_json_candidates(text: str) -> List[str]:\n",
            "    text = strip_markdown_fences(text)\n",
            "    candidates: List[str] = []\n",
            "    pairs = {\"{\": \"}\", \"[\": \"]\"}\n",
            "    for start, char in enumerate(text):\n",
            "        if char not in pairs:\n",
            "            continue\n",
            "        expected_stack = [pairs[char]]\n",
            "        in_string = False\n",
            "        escaped = False\n",
            "        for index in range(start + 1, len(text)):\n",
            "            current = text[index]\n",
            "            if escaped:\n",
            "                escaped = False\n",
            "                continue\n",
            "            if current == \"\\\\\":\n",
            "                escaped = True\n",
            "                continue\n",
            "            if current == '\\\"':\n",
            "                in_string = not in_string\n",
            "                continue\n",
            "            if in_string:\n",
            "                continue\n",
            "            if current in pairs:\n",
            "                expected_stack.append(pairs[current])\n",
            "            elif expected_stack and current == expected_stack[-1]:\n",
            "                expected_stack.pop()\n",
            "                if not expected_stack:\n",
            "                    candidates.append(text[start : index + 1])\n",
            "                    break\n",
            "    return candidates\n",
            "\n",
            "def extract_json_object(text: str) -> Any:\n",
            "    text = strip_markdown_fences(text)\n",
            "    decoder = json.JSONDecoder()\n",
            "    for candidate in [text, *extract_balanced_json_candidates(text)]:\n",
            "        candidate = candidate.strip()\n",
            "        if not candidate:\n",
            "            continue\n",
            "        try:\n",
            "            parsed, _ = decoder.raw_decode(candidate)\n",
            "            return parsed\n",
            "        except json.JSONDecodeError:\n",
            "            pass\n",
            "    raise ValueError(\"No JSON object found\")\n",
            "\n",
            "def schema_default(schema: Dict[str, Any]) -> Any:\n",
            "    schema_type = schema.get(\"type\")\n",
            "    if schema_type == \"object\":\n",
            "        result: Dict[str, Any] = {}\n",
            "        properties = schema.get(\"properties\", {})\n",
            "        for key in schema.get(\"required\", []):\n",
            "            result[key] = schema_default(properties.get(key, {}))\n",
            "        return result\n",
            "    if schema_type == \"array\":\n",
            "        return []\n",
            "    if schema_type in (\"number\", \"integer\"):\n",
            "        return 0\n",
            "    if schema_type == \"boolean\":\n",
            "        return False\n",
            "    return \"\"\n",
            "\n",
            "def normalize_payload_for_schema(payload: Any, schema: Dict[str, Any]) -> Dict[str, Any]:\n",
            "    if isinstance(payload, list) and schema.get(\"type\") == \"object\" and \"items\" in schema.get(\"properties\", {}):\n",
            "        payload = {\"items\": payload}\n",
            "    if not isinstance(payload, dict):\n",
            "        payload = schema_default(schema)\n",
            "    properties = schema.get(\"properties\", {})\n",
            "    for key in schema.get(\"required\", []):\n",
            "        if key not in payload or payload[key] is None:\n",
            "            payload[key] = schema_default(properties.get(key, {}))\n",
            "    return payload\n"
        ]
    })

    # 06_GENERATION LOGIC
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def enriched_section_text(section: SectionData) -> str:\n",
            "    parts = [f\"Section Title: {section.title}\", section.content]\n",
            "    if section.equations:\n",
            "        parts.append(\"Equations:\\n\" + \"\\n\".join(section.equations[:20]))\n",
            "    if section.tables:\n",
            "        table_lines = [json.dumps(t, ensure_ascii=False)[:2500] for t in section.tables[:5]]\n",
            "        parts.append(\"Tables:\\n\" + \"\\n\".join(table_lines))\n",
            "    captions = [f\"{fig.figure_id}: {fig.caption} (Image Path: {fig.image_path})\" for fig in section.figures]\n",
            "    if captions:\n",
            "        parts.append(\"Figure references:\\n\" + \"\\n\".join(captions[:20]))\n",
            "    return \"\\n\\n\".join(part for part in parts if part).strip()\n",
            "\n",
            "def prompt_for_artifact(section: SectionData, artifact_name: str, schema: Dict[str, Any]) -> str:\n",
            "    source_text = enriched_section_text(section)[:12000]\n",
            "    image_note = \"\"\n",
            "    if artifact_name == \"image_captions\":\n",
            "        image_note = \"\\nImage caption generation rules:\\n- Use only Docling-extracted figure references, existing captions, and nearby section text.\\n- Do not claim to visually inspect pixels.\\n- If a figure has no usable extracted context, return a conservative caption and low confidence.\\n- Preserve figure_id values exactly.\\n\"\n",
            "    return f\"\"\"\\\n",
            "You are generating curriculum artifacts for offline school tutoring.\n",
            "Use only the Docling-extracted source section, including tables, equations, and figure captions.\n",
            "Do not invent facts.\n",
            "{image_note}\n",
            "CRITICAL OUTPUT RULES:\n",
            "- Return exactly ONE valid JSON object.\n",
            "- The first character must be {{ and the last character must be }}.\n",
            "- Do not use markdown fences.\n",
            "- Do not include explanations before or after JSON.\n",
            "- If source is insufficient, return the required keys with empty arrays or empty strings.\n",
            "\n",
            "Artifact: {artifact_name}\n",
            "Required JSON Schema: {json.dumps(schema, ensure_ascii=False)}\n",
            "\n",
            "Source:\n",
            "{source_text}\n",
            "\"\"\"\n",
            "\n",
            "def generate_json(section: SectionData, artifact_name: str, spec: dict) -> Dict[str, Any]:\n",
            "    digest = hashlib.sha256((section.section_id + artifact_name + section.content).encode(\"utf-8\")).hexdigest()\n",
            "    cpath = CACHE_ROOT / f\"{digest}.json\"\n",
            "    \n",
            "    if CONFIG[\"resume\"] and cpath.exists():\n",
            "        return json.loads(cpath.read_text(encoding=\"utf-8\"))\n",
            "\n",
            "    schema = spec['schema']\n",
            "    base_prompt = prompt_for_artifact(section, artifact_name, schema)\n",
            "    last_error = \"\"\n",
            "    max_retries = max(1, int(CONFIG[\"max_retries\"]))\n",
            "    \n",
            "    for retry in range(max_retries):\n",
            "        prompt = base_prompt if retry == 0 else base_prompt + f\"\\n\\nYour previous response was invalid because: {last_error}\\nReturn corrected JSON only.\"\n",
            "        result = CONTENT_LLM(prompt, max_tokens=CONFIG[\"max_tokens\"], temperature=CONFIG[\"temperature\"], top_p=CONFIG[\"top_p\"])\n",
            "        raw = result[\"choices\"][0][\"text\"]\n",
            "        try:\n",
            "            parsed = normalize_payload_for_schema(extract_json_object(raw), schema)\n",
            "            jsonschema_validate(parsed, schema)\n",
            "            cpath.write_text(json.dumps(parsed, indent=2, ensure_ascii=False), encoding=\"utf-8\")\n",
            "            return parsed\n",
            "        except Exception as exc:\n",
            "            last_error = str(exc)\n",
            "    \n",
            "    payload = normalize_payload_for_schema(schema_default(schema), schema)\n",
            "    payload[\"_generation_failed\"] = True\n",
            "    payload[\"_failure_reason\"] = last_error\n",
            "    cpath.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding=\"utf-8\")\n",
            "    return payload\n",
            "\n",
            "all_artifacts = {}\n",
            "VALIDATION_REPORT = {\"total_sections\": 0, \"successful_artifacts\": {}, \"failed_artifacts\": {}, \"errors\": []}\n",
            "start_time = time.time()\n",
            "\n",
            "for chapter in tqdm(CHAPTERS, desc=\"Chapters\"):\n",
            "    for section in tqdm(chapter.sections, desc=f\"Sections: {chapter.chapter_title}\", leave=False):\n",
            "        VALIDATION_REPORT[\"total_sections\"] += 1\n",
            "        for artifact_name, spec in ARTIFACT_SPECS.items():\n",
            "            if CONFIG.get(spec[\"enabled\"], False):\n",
            "                payload = generate_json(section, artifact_name, spec)\n",
            "                all_artifacts.setdefault(artifact_name, []).append({\"section_id\": section.section_id, \"chapter_id\": chapter.document_id, \"payload\": payload})\n",
            "                if payload.get(\"_generation_failed\"):\n",
            "                    VALIDATION_REPORT[\"failed_artifacts\"][artifact_name] = VALIDATION_REPORT[\"failed_artifacts\"].get(artifact_name, 0) + 1\n",
            "                    VALIDATION_REPORT[\"errors\"].append({\"section_id\": section.section_id, \"artifact\": artifact_name, \"error\": payload.get(\"_failure_reason\")})\n",
            "                else:\n",
            "                    VALIDATION_REPORT[\"successful_artifacts\"][artifact_name] = VALIDATION_REPORT[\"successful_artifacts\"].get(artifact_name, 0) + 1\n",
            "\n",
            "for artifact_name, spec in ARTIFACT_SPECS.items():\n",
            "    if CONFIG.get(spec[\"enabled\"], False):\n",
            "        output_file = PACK_ROOT / spec[\"file\"]\n",
            "        output_file.write_text(json.dumps(all_artifacts.get(artifact_name, []), indent=2, ensure_ascii=False), encoding=\"utf-8\")\n",
            "\n",
            "VALIDATION_REPORT[\"total_time_seconds\"] = round(time.time() - start_time, 2)\n",
            "(PACK_ROOT / \"generation_report.json\").write_text(json.dumps(VALIDATION_REPORT, indent=2), encoding=\"utf-8\")\n",
            "print(\"LLM JSON Generation complete. Validation report saved.\")\n"
        ]
    })

    # 07_FINAL_ZIP
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "zip_path = OUTPUT_ROOT / CONFIG[\"artifact_zip_name\"]\n",
            "with zipfile.ZipFile(zip_path, \"w\", zipfile.ZIP_DEFLATED) as archive:\n",
            "    for file_path in PACK_ROOT.rglob(\"*.json\"):\n",
            "        archive.write(file_path, arcname=str(file_path.relative_to(PACK_ROOT.parent)))\n",
            "print(\"Process complete. Final zip saved to\", zip_path)\n"
        ]
    })
    
    with open('/home/akash/Desktop/PIHUB/02_ARTIFACT_GENERATION.ipynb', 'w') as f:
        json.dump({"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}, f, indent=2)


def build_03():
    cells = []
    
    # 00_MARKDOWN
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 3: Targeted Voice Artifact Synthesis\n",
            "This notebook parses the generated JSON artifacts to synthesize high-value voice files (flashcards, summaries, etc.) using Svara TTS."
        ]
    })
    
    # 01_SETUP
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "CONFIG = {\n",
            "    \"output_root\": \"/kaggle/working/idp_curriculum_generation\",\n",
            "}\n",
            "from pathlib import Path\n",
            "OUTPUT_ROOT = Path(CONFIG[\"output_root\"])\n",
            "PACK_ROOT = OUTPUT_ROOT / \"generated_pack\"\n",
            "VOICE_ROOT = PACK_ROOT / \"voice\"\n",
            "STRUCTURED_ROOT = OUTPUT_ROOT / \"structured_chapters\"\n"
        ]
    })
    
    # 02_NPM
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "!npm init -y\n",
            "!npm install @huggingface/transformers onnxruntime-node\n",
            "from huggingface_hub import hf_hub_download\n",
            "snac_decoder_path = hf_hub_download(repo_id=\"hubertsiuzdak/snac_24khz-ONNX\", filename=\"onnx/decoder_model.onnx\")\n",
            "print(\"Downloaded SNAC Decoder ONNX to:\", snac_decoder_path)\n"
        ]
    })

    # 03_SVARA_JS_SCRIPT
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "svara_js_code = f\"\"\"\n",
            "import fs from 'node:fs';\n",
            "import path from 'node:path';\n",
            "import * as ort from 'onnxruntime-node';\n",
            "import {{ AutoModelForCausalLM, AutoTokenizer, Tensor }} from '@huggingface/transformers';\n",
            "\n",
            "const PACK_DIR = '{PACK_ROOT}';\n",
            "const VOICE_DIR = '{VOICE_ROOT}';\n",
            "const MODEL_ID = 'shreyask/svara-tts-v1-ONNX';\n",
            "const SNAC_DECODER = '{snac_decoder_path}';\n",
            "const SAMPLE_RATE = 24000;\n",
            "const PAUSE_SAMPLES = 1.5 * SAMPLE_RATE; // 1.5 seconds\n",
            "\n",
            "let report = {{\n",
            "  total_files: 0,\n",
            "  start_time: Date.now(),\n",
            "  errors: [],\n",
            "  categories: {{ section_summaries: 0, concepts: 0, glossary: 0, faqs: 0, doubts: 0, flashcards: 0, full_narration: 0 }}\n",
            "}};\n",
            "\n",
            "function wavBuffer(floatSamples, sampleRate) {{\n",
            "  const n = floatSamples.length;\n",
            "  const buffer = Buffer.alloc(44 + n * 2);\n",
            "  buffer.write('RIFF', 0);\n",
            "  buffer.writeUInt32LE(36 + n * 2, 4);\n",
            "  buffer.write('WAVE', 8);\n",
            "  buffer.write('fmt ', 12);\n",
            "  buffer.writeUInt32LE(16, 16);\n",
            "  buffer.writeUInt16LE(1, 20);\n",
            "  buffer.writeUInt16LE(1, 22);\n",
            "  buffer.writeUInt32LE(sampleRate, 24);\n",
            "  buffer.writeUInt32LE(sampleRate * 2, 28);\n",
            "  buffer.writeUInt16LE(2, 32);\n",
            "  buffer.writeUInt16LE(16, 34);\n",
            "  buffer.write('data', 36);\n",
            "  buffer.writeUInt32LE(n * 2, 40);\n",
            "  for (let i = 0; i < n; i++) {{\n",
            "    const clamped = Math.max(-1, Math.min(1, Number(floatSamples[i])));\n",
            "    buffer.writeInt16LE(Math.round(clamped * 32767), 44 + i * 2);\n",
            "  }}\n",
            "  return buffer;\n",
            "}}\n",
            "\n",
            "function extractSnacCodes(fullOutput, inputLength) {{\n",
            "  const generated = fullOutput.slice(inputLength).map(Number);\n",
            "  const sosIndex = generated.indexOf(128257);\n",
            "  const start = sosIndex >= 0 ? sosIndex + 1 : 0;\n",
            "  const audio = [];\n",
            "  let bandPos = 0;\n",
            "  for (const token of generated.slice(start)) {{\n",
            "    if (token === 128258) break;\n",
            "    if (token < 128266 || token >= 156938) continue;\n",
            "    const band = bandPos % 7;\n",
            "    const code = token - 128266 - band * 4096;\n",
            "    if (code >= 0 && code < 4096) {{\n",
            "      audio.push({{ band, code }});\n",
            "      bandPos += 1;\n",
            "    }}\n",
            "  }}\n",
            "  const frameCount = Math.floor(audio.length / 7);\n",
            "  const level0 = []; const level1 = []; const level2 = [];\n",
            "  for (let frame = 0; frame < frameCount; frame++) {{\n",
            "    const codes = audio.slice(frame * 7, frame * 7 + 7).map((x) => x.code);\n",
            "    level0.push(codes[0]); level1.push(codes[1], codes[4]); level2.push(codes[2], codes[3], codes[5], codes[6]);\n",
            "  }}\n",
            "  return {{ frameCount, level0, level1, level2 }};\n",
            "}}\n",
            "\n",
            "async function decodeSnac(decoder, codes) {{\n",
            "  if (codes.frameCount < 1) return new Float32Array(0);\n",
            "  const feeds = {{\n",
            "    'audio_codes.0': new ort.Tensor('int64', BigInt64Array.from(codes.level0.map(BigInt)), [1, codes.level0.length]),\n",
            "    'audio_codes.1': new ort.Tensor('int64', BigInt64Array.from(codes.level1.map(BigInt)), [1, codes.level1.length]),\n",
            "    'audio_codes.2': new ort.Tensor('int64', BigInt64Array.from(codes.level2.map(BigInt)), [1, codes.level2.length]),\n",
            "  }};\n",
            "  const output = await decoder.run(feeds);\n",
            "  return output.audio_values.data;\n",
            "}}\n",
            "\n",
            "function chunkText(text, maxWords = 20) {{\n",
            "  if (!text) return [];\n",
            "  const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];\n",
            "  let chunks = [];\n",
            "  let curr = \"\";\n",
            "  for (let s of sentences) {{\n",
            "    if (curr.split(' ').length + s.split(' ').length > maxWords && curr.length > 0) {{\n",
            "      chunks.push(curr.trim()); curr = s;\n",
            "    }} else {{\n",
            "      curr += \" \" + s;\n",
            "    }}\n",
            "  }}\n",
            "  if (curr.trim().length > 0) chunks.push(curr.trim());\n",
            "  return chunks;\n",
            "}}\n",
            "\n",
            "async function synthesizeWav(model, tokenizer, decoder, textChunks, outputPath, category, insertPauseBetween = false) {{\n",
            "  if (fs.existsSync(outputPath)) return outputPath;\n",
            "  console.log(`Synthesizing [${{category}}]: ${{outputPath}}`);\n",
            "  let combinedSamples = [];\n",
            "  for (let i = 0; i < textChunks.length; i++) {{\n",
            "    let chunk = textChunks[i].trim();\n",
            "    if (!chunk) continue;\n",
            "    try {{\n",
            "      const body = tokenizer.encode(`English (Indian) (Female): ${{chunk}}`, {{ add_special_tokens: false }});\n",
            "      const ids = [128259, tokenizer.bos_token_id, ...body, 128009, 128260];\n",
            "      const out = await model.generate({{\n",
            "        inputs: new Tensor('int64', BigInt64Array.from(ids.map(BigInt)), [1, ids.length]),\n",
            "        max_new_tokens: 200, do_sample: true, temperature: 0.6, top_p: 0.9, top_k: 40, eos_token_id: 128258,\n",
            "      }});\n",
            "      const codes = extractSnacCodes(Array.from(out.data), ids.length);\n",
            "      const audio = await decodeSnac(decoder, codes);\n",
            "      for(let val of audio) combinedSamples.push(val);\n",
            "      \n",
            "      if (insertPauseBetween && i < textChunks.length - 1) {{\n",
            "        for (let p = 0; p < PAUSE_SAMPLES; p++) combinedSamples.push(0.0);\n",
            "      }}\n",
            "    }} catch (e) {{ \n",
            "      console.error('Failed chunk:', e.message);\n",
            "      report.errors.push(`Chunk error in ${{outputPath}}: ${{e.message}}`);\n",
            "    }}\n",
            "  }}\n",
            "  if (combinedSamples.length > 0) {{\n",
            "    fs.writeFileSync(outputPath, wavBuffer(combinedSamples, SAMPLE_RATE));\n",
            "    report.total_files++;\n",
            "    if (report.categories[category] !== undefined) report.categories[category]++;\n",
            "    return outputPath;\n",
            "  }}\n",
            "  report.errors.push(`Failed to generate any audio for ${{outputPath}}`);\n",
            "  return null;\n",
            "}}\n",
            "\n",
            "function cleanSlug(text) {{\n",
            "  return text.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').substring(0, 50);\n",
            "}}\n",
            "\n",
            "async function main() {{\n",
            "  console.log(`Loading Svara TTS model...`);\n",
            "  const tokenizer = await AutoTokenizer.from_pretrained(MODEL_ID);\n",
            "  const model = await AutoModelForCausalLM.from_pretrained(MODEL_ID, {{\n",
            "    dtype: 'q4f16', device: 'cpu', use_external_data_format: true,\n",
            "  }});\n",
            "  const decoder = await ort.InferenceSession.create(SNAC_DECODER, {{ executionProviders: ['cpu'] }});\n",
            "  \n",
            "  const readJSON = (f) => {{ try {{ return JSON.parse(fs.readFileSync(path.join(PACK_DIR, f), 'utf-8')); }} catch(e) {{ return []; }} }};\n",
            "  \n",
            "  // Make Dirs\n",
            "  const dirs = ['section_summaries', 'concepts', 'glossary', 'faqs', 'doubts', 'flashcards'];\n",
            "  for(let d of dirs) fs.mkdirSync(path.join(VOICE_DIR, d), {{ recursive: true }});\n",
            "  \n",
            "  let manifest = {{ chapter_id: 'unknown', summary: '', objectives: '', full_narration: '', sections: [], concepts: [], glossary: [], faqs: [], doubts: [], flashcards: [] }};\n",
            "  \n",
            "  // 1. SECTION SUMMARIES & FULL CHAPTER SUMMARY\n",
            "  let summaries = readJSON('summary.json');\n",
            "  let allSummaries = [];\n",
            "  for (let s of summaries) {{\n",
            "    if(s.chapter_id) manifest.chapter_id = s.chapter_id;\n",
            "    let text = s.payload && s.payload.summary ? s.payload.summary : \"\";\n",
            "    if (text) {{\n",
            "      allSummaries.push(text);\n",
            "      let p = path.join('section_summaries', `${{s.section_id}}.wav`);\n",
            "      if(await synthesizeWav(model, tokenizer, decoder, chunkText(text), path.join(VOICE_DIR, p), 'section_summaries'))\n",
            "        manifest.sections.push(p);\n",
            "    }}\n",
            "  }}\n",
            "  if (allSummaries.length > 0) {{\n",
            "    let p = 'chapter_summary.wav';\n",
            "    if(await synthesizeWav(model, tokenizer, decoder, chunkText(allSummaries.join(' ')), path.join(VOICE_DIR, p), 'section_summaries'))\n",
            "      manifest.summary = p;\n",
            "  }}\n",
            "\n",
            "  // 2. LEARNING OBJECTIVES\n",
            "  let objectives = readJSON('learning_objectives.json');\n",
            "  let objText = objectives.map(o => (o.payload && o.payload.items ? o.payload.items : []).map(i => i.objective).join('. ')).join('. ');\n",
            "  if (objText.trim()) {{\n",
            "    let p = 'learning_objectives.wav';\n",
            "    if(await synthesizeWav(model, tokenizer, decoder, chunkText(objText), path.join(VOICE_DIR, p), 'section_summaries'))\n",
            "      manifest.objectives = p;\n",
            "  }}\n",
            "\n",
            "  // 3. CONCEPTS\n",
            "  let concepts = readJSON('concepts.json');\n",
            "  for (let s of concepts) {{\n",
            "    for (let item of (s.payload && s.payload.items ? s.payload.items : [])) {{\n",
            "      let text = item.concept;\n",
            "      if (!text) continue;\n",
            "      let p = path.join('concepts', `${{cleanSlug(text)}}.wav`);\n",
            "      if(await synthesizeWav(model, tokenizer, decoder, chunkText(text), path.join(VOICE_DIR, p), 'concepts'))\n",
            "        manifest.concepts.push(p);\n",
            "    }}\n",
            "  }}\n",
            "\n",
            "  // 4. GLOSSARY\n",
            "  let glossary = readJSON('glossary.json');\n",
            "  for (let s of glossary) {{\n",
            "    for (let item of (s.payload && s.payload.items ? s.payload.items : [])) {{\n",
            "      if (!item.term) continue;\n",
            "      let text = `${{item.term}}. ${{item.definition}}`;\n",
            "      let p = path.join('glossary', `${{cleanSlug(item.term)}}.wav`);\n",
            "      if(await synthesizeWav(model, tokenizer, decoder, chunkText(text), path.join(VOICE_DIR, p), 'glossary'))\n",
            "        manifest.glossary.push(p);\n",
            "    }}\n",
            "  }}\n",
            "\n",
            "  // 5. FAQS\n",
            "  let faqs = readJSON('faqs.json');\n",
            "  let fIdx = 1;\n",
            "  for (let s of faqs) {{\n",
            "    for (let item of (s.payload && s.payload.items ? s.payload.items : [])) {{\n",
            "      let text = `${{item.question}} ${{item.answer}}`;\n",
            "      let p = path.join('faqs', `faq_${{fIdx.toString().padStart(3, '0')}}.wav`);\n",
            "      if(await synthesizeWav(model, tokenizer, decoder, chunkText(text), path.join(VOICE_DIR, p), 'faqs'))\n",
            "        manifest.faqs.push(p);\n",
            "      fIdx++;\n",
            "    }}\n",
            "  }}\n",
            "\n",
            "  // 6. DOUBTS\n",
            "  let doubts = readJSON('common_doubts.json');\n",
            "  let dIdx = 1;\n",
            "  for (let s of doubts) {{\n",
            "    for (let item of (s.payload && s.payload.items ? s.payload.items : [])) {{\n",
            "      let text = `${{item.doubt}} ${{item.clarification}}`;\n",
            "      let p = path.join('doubts', `doubt_${{dIdx.toString().padStart(3, '0')}}.wav`);\n",
            "      if(await synthesizeWav(model, tokenizer, decoder, chunkText(text), path.join(VOICE_DIR, p), 'doubts'))\n",
            "        manifest.doubts.push(p);\n",
            "      dIdx++;\n",
            "    }}\n",
            "  }}\n",
            "\n",
            "  // 7. FLASHCARDS (with pause)\n",
            "  let flashcards = readJSON('flashcards.json');\n",
            "  let fcIdx = 1;\n",
            "  for (let s of flashcards) {{\n",
            "    for (let item of (s.payload && s.payload.items ? s.payload.items : [])) {{\n",
            "      if (!item.question || !item.answer) continue;\n",
            "      let p = path.join('flashcards', `flashcard_${{fcIdx.toString().padStart(3, '0')}}.wav`);\n",
            "      let parts = chunkText(item.question).concat(chunkText(item.answer));\n",
            "      if(await synthesizeWav(model, tokenizer, decoder, parts, path.join(VOICE_DIR, p), 'flashcards', true))\n",
            "        manifest.flashcards.push(p);\n",
            "      fcIdx++;\n",
            "    }}\n",
            "  }}\n",
            "\n",
            "  // 8. FULL CHAPTER NARRATION (from structured_chapter.json)\n",
            "  let fullText = \"\";\n",
            "  let structuredChaptersPath = '{STRUCTURED_ROOT}';\n",
            "  const recurseDirs = (dir) => {{\n",
            "      if (!fs.existsSync(dir)) return;\n",
            "      let files = fs.readdirSync(dir);\n",
            "      for(let f of files) {{\n",
            "          let p = path.join(dir, f);\n",
            "          if(fs.statSync(p).isDirectory()) recurseDirs(p);\n",
            "          else if(f === 'structured_chapter.json') {{\n",
            "             try {{\n",
            "                 let j = JSON.parse(fs.readFileSync(p));\n",
            "                 for(let sec of j.sections) fullText += sec.content + \". \";\n",
            "             }} catch(e){{}}\n",
            "          }}\n",
            "      }}\n",
            "  }};\n",
            "  recurseDirs(structuredChaptersPath);\n",
            "  if (fullText.trim()) {{\n",
            "     let p = 'full_chapter.wav';\n",
            "     if(await synthesizeWav(model, tokenizer, decoder, chunkText(fullText, 30), path.join(VOICE_DIR, p), 'full_narration'))\n",
            "         manifest.full_narration = p;\n",
            "  }}\n",
            "\n",
            "  // Write manifest and report\n",
            "  fs.writeFileSync(path.join(VOICE_DIR, 'voice_manifest.json'), JSON.stringify(manifest, null, 2));\n",
            "  report.total_time_seconds = Math.round((Date.now() - report.start_time) / 1000);\n",
            "  fs.writeFileSync(path.join(VOICE_DIR, 'voice_generation_report.json'), JSON.stringify(report, null, 2));\n",
            "  console.log('Voice manifest and generation report generated!');\n",
            "  console.log(JSON.stringify(report, null, 2));\n",
            "}}\n",
            "main().catch(console.error);\n",
            "\"\"\"\n",
            "\n",
            "with open(OUTPUT_ROOT / \"generate_audio.mjs\", \"w\") as f:\n",
            "    f.write(svara_js_code)\n",
            "\n",
            "!node {OUTPUT_ROOT}/generate_audio.mjs\n"
        ]
    })

    # 04_FINAL_ZIP
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import zipfile\n",
            "zip_path = OUTPUT_ROOT / \"generated_pack_with_voice.zip\"\n",
            "with zipfile.ZipFile(zip_path, \"w\", zipfile.ZIP_DEFLATED) as archive:\n",
            "    # Add all JSON artifacts\n",
            "    for file_path in PACK_ROOT.rglob(\"*.json\"):\n",
            "        archive.write(file_path, arcname=str(file_path.relative_to(PACK_ROOT.parent)))\n",
            "    # Add all Audio artifacts and manifest\n",
            "    for file_path in VOICE_ROOT.rglob(\"*.wav\"):\n",
            "        archive.write(file_path, arcname=str(file_path.relative_to(PACK_ROOT.parent)))\n",
            "    voice_manifest = VOICE_ROOT / \"voice_manifest.json\"\n",
            "    if voice_manifest.exists():\n",
            "        archive.write(voice_manifest, arcname=str(voice_manifest.relative_to(PACK_ROOT.parent)))\n",
            "    voice_report = VOICE_ROOT / \"voice_generation_report.json\"\n",
            "    if voice_report.exists():\n",
            "        archive.write(voice_report, arcname=str(voice_report.relative_to(PACK_ROOT.parent)))\n",
            "print(\"Process complete. Final zip saved to\", zip_path)\n"
        ]
    })
    
    with open('/home/akash/Desktop/PIHUB/03_VOICE_GENERATION.ipynb', 'w') as f:
        json.dump({"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}, f, indent=2)

build_02()
build_03()
