import json

def build_02():
    cells = []
    
    # 00_MARKDOWN
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 2: LLM Artifact Generation\n",
            "\n",
            "This notebook runs Gemma to generate highly structured educational artifacts with strict quantity targets.\n"
        ]
    })
    
    # 01_CONFIG
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "CONFIG = {\n",
            "    \"output_root\": \"/kaggle/working/idp_curriculum_generation\",\n",
            "    \"content_model_repo\": \"lmstudio-community/gemma-4-12B-it-GGUF\",\n",
            "    \"content_model_file\": \"gemma-4-12B-it-Q4_K_M.gguf\",\n",
            "\n",
            "    # Generation controls.\n",
            "    \"generate_concepts\": True,\n",
            "    \"generate_learning_objectives\": True,\n",
            "    \"generate_glossary\": True,\n",
            "    \"generate_summary\": True,\n",
            "    \"generate_detailed_explanation\": True,\n",
            "    \"generate_misconceptions\": True,\n",
            "    \"generate_mcq_quiz\": True,\n",
            "    \"generate_short_answer\": True,\n",
            "    \"generate_flashcards\": True,\n",
            "    \"generate_concept_relationships\": True,\n",
            "    \"generate_image_captions\": True,\n",
            "    \"generate_investigations\": True,\n",
            "    \"generate_teacher_notes\": True,\n",
            "    \"generate_prerequisites\": True,\n",
            "    \"generate_difficulty_analysis\": True,\n",
            "    \"generate_faqs\": True,\n",
            "    \"generate_common_doubts\": True,\n",
            "    \"generate_exam_questions\": True,\n",
            "\n",
            "    # llama.cpp generation settings.\n",
            "    \"temperature\": 0.2,\n",
            "    \"top_p\": 0.9,\n",
            "    \"max_tokens\": 1200,\n",
            "    \"context_size\": 8192,\n",
            "    \"n_gpu_layers\": -1,\n",
            "    \"n_threads\": 4,\n",
            "    \"max_retries\": 3,\n",
            "    \"resume\": True,\n",
            "    \"artifact_zip_name\": \"generated_pack.zip\"\n",
            "}\n"
        ]
    })
    
    # 02_ENV
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "!pip -q install llama-cpp-python jsonschema pandas tqdm huggingface_hub\n",
            "\n",
            "import json, logging, os, re, time, hashlib, zipfile\n",
            "from dataclasses import dataclass, field\n",
            "from pathlib import Path\n",
            "from typing import Any, Dict, List\n",
            "from tqdm.auto import tqdm\n",
            "from jsonschema import validate as jsonschema_validate\n",
            "\n",
            "OUTPUT_ROOT = Path(CONFIG[\"output_root\"])\n",
            "CACHE_ROOT = OUTPUT_ROOT / \"cache\"\n",
            "STRUCTURED_ROOT = OUTPUT_ROOT / \"structured_chapters\"\n",
            "PACK_ROOT = OUTPUT_ROOT / \"generated_pack\"\n",
            "\n",
            "for path in [CACHE_ROOT, PACK_ROOT]:\n",
            "    path.mkdir(parents=True, exist_ok=True)\n"
        ]
    })
    
    # 03_LOAD_CHAPTERS
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "@dataclass\n",
            "class FigureData:\n",
            "    figure_id: str\n",
            "    caption: str = \"\"\n",
            "    image_path: str = \"\"\n",
            "\n",
            "@dataclass\n",
            "class SectionData:\n",
            "    section_id: str\n",
            "    title: str\n",
            "    content: str\n",
            "    tables: List[Dict[str, Any]] = field(default_factory=list)\n",
            "    figures: List[FigureData] = field(default_factory=list)\n",
            "    equations: List[str] = field(default_factory=list)\n",
            "\n",
            "@dataclass\n",
            "class ChapterData:\n",
            "    document_id: str\n",
            "    chapter_title: str\n",
            "    grade: str\n",
            "    subject: str\n",
            "    sections: List[SectionData]\n",
            "\n",
            "CHAPTERS = []\n",
            "for p in STRUCTURED_ROOT.rglob(\"structured_chapter.json\"):\n",
            "    raw = json.loads(p.read_text(encoding=\"utf-8\"))\n",
            "    sections = []\n",
            "    for s in raw.get(\"sections\", []):\n",
            "        figs = [FigureData(**f) for f in s.get(\"figures\", [])]\n",
            "        sections.append(SectionData(s[\"section_id\"], s[\"title\"], s[\"content\"], s.get(\"tables\", []), figs, s.get(\"equations\", [])))\n",
            "    CHAPTERS.append(ChapterData(raw[\"document_id\"], raw[\"chapter_title\"], raw[\"grade\"], raw[\"subject\"], sections))\n",
            "\n",
            "print(f\"Loaded {len(CHAPTERS)} structured chapters.\")\n"
        ]
    })
    
    # 04_MODEL
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from llama_cpp import Llama\n",
            "\n",
            "try:\n",
            "    CONTENT_LLM = Llama.from_pretrained(\n",
            "        repo_id=CONFIG[\"content_model_repo\"],\n",
            "        filename=CONFIG[\"content_model_file\"],\n",
            "        n_ctx=int(CONFIG[\"context_size\"]),\n",
            "        n_gpu_layers=int(CONFIG[\"n_gpu_layers\"]),\n",
            "        n_threads=int(CONFIG[\"n_threads\"]),\n",
            "        verbose=False,\n",
            "    )\n",
            "    print(\"Model loaded successfully!\")\n",
            "except Exception as e:\n",
            "    print(f\"Failed to load model: {e}\")\n"
        ]
    })

    # 05_GENERATION_SCHEMA_LOGIC
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "ARTIFACT_SPECS: Dict[str, Dict[str, Any]] = {\n",
            "    \"concepts\": {\"enabled\": \"generate_concepts\", \"file\": \"concepts.json\", \"target_calc\": lambda n: max(1, 20//n), \"target_msg\": \"Generate exactly {T} concepts from this section.\", \"schema\": {\"type\": \"object\", \"required\": [\"concepts\"], \"properties\": {\"concepts\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"id\", \"name\", \"definition\", \"importance\", \"section\", \"keywords\"], \"properties\": {\"id\": {\"type\": \"string\"}, \"name\": {\"type\": \"string\"}, \"definition\": {\"type\": \"string\"}, \"importance\": {\"type\": \"string\", \"enum\": [\"high\", \"medium\", \"low\"]}, \"section\": {\"type\": \"string\"}, \"keywords\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"learning_objectives\": {\"enabled\": \"generate_learning_objectives\", \"file\": \"learning_objectives.json\", \"target_calc\": lambda n: max(1, 8//n), \"target_msg\": \"Generate exactly {T} learning objectives using Bloom's Taxonomy.\", \"schema\": {\"type\": \"object\", \"required\": [\"learning_objectives\"], \"properties\": {\"learning_objectives\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"id\", \"objective\", \"blooms_level\", \"difficulty\"], \"properties\": {\"id\": {\"type\": \"string\"}, \"objective\": {\"type\": \"string\"}, \"blooms_level\": {\"type\": \"string\"}, \"difficulty\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"glossary\": {\"enabled\": \"generate_glossary\", \"file\": \"glossary.json\", \"target_calc\": lambda n: max(1, 35//n), \"target_msg\": \"Generate exactly {T} glossary terms with definition and example.\", \"schema\": {\"type\": \"object\", \"required\": [\"glossary\"], \"properties\": {\"glossary\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"term\", \"definition\", \"example\"], \"properties\": {\"term\": {\"type\": \"string\"}, \"definition\": {\"type\": \"string\"}, \"example\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"summary\": {\"enabled\": \"generate_summary\", \"file\": \"summary.json\", \"target_calc\": lambda n: 1, \"target_msg\": \"Generate exactly 1 short summary (150-300 words) and 1 detailed summary (600-1200 words) for this section.\", \"schema\": {\"type\": \"object\", \"required\": [\"summary_short\", \"summary_detailed\"], \"properties\": {\"summary_short\": {\"type\": \"string\"}, \"summary_detailed\": {\"type\": \"string\"}}}},\n",
            "    \"detailed_explanation\": {\"enabled\": \"generate_detailed_explanation\", \"file\": \"detailed_explanation.json\", \"target_calc\": lambda n: 1, \"target_msg\": \"Generate exactly 1 detailed explanation (500-1500 words) with examples, analogies, and applications.\", \"schema\": {\"type\": \"object\", \"required\": [\"section_id\", \"explanation\"], \"properties\": {\"section_id\": {\"type\": \"string\"}, \"explanation\": {\"type\": \"string\"}}}},\n",
            "    \"misconceptions\": {\"enabled\": \"generate_misconceptions\", \"file\": \"misconceptions.json\", \"target_calc\": lambda n: max(1, 15//n), \"target_msg\": \"Generate exactly {T} misconceptions and corrections.\", \"schema\": {\"type\": \"object\", \"required\": [\"misconceptions\"], \"properties\": {\"misconceptions\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"misconception\", \"correction\", \"why_students_confuse_it\"], \"properties\": {\"misconception\": {\"type\": \"string\"}, \"correction\": {\"type\": \"string\"}, \"why_students_confuse_it\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"mcq_quiz\": {\"enabled\": \"generate_mcq_quiz\", \"file\": \"mcq_quiz.json\", \"target_calc\": lambda n: max(1, 25//n), \"target_msg\": \"Generate exactly {T} MCQs (mix of easy/medium/hard).\", \"schema\": {\"type\": \"object\", \"required\": [\"mcqs\"], \"properties\": {\"mcqs\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"question\", \"options\", \"correct_answer\", \"explanation\", \"difficulty\"], \"properties\": {\"question\": {\"type\": \"string\"}, \"options\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"correct_answer\": {\"type\": \"string\"}, \"explanation\": {\"type\": \"string\"}, \"difficulty\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"short_answer_questions\": {\"enabled\": \"generate_short_answer\", \"file\": \"short_answer_questions.json\", \"target_calc\": lambda n: max(1, 15//n), \"target_msg\": \"Generate exactly {T} short answer questions (mix of 1, 2, and 5 marks).\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"question\", \"sample_answer\", \"marks\"], \"properties\": {\"question\": {\"type\": \"string\"}, \"sample_answer\": {\"type\": \"string\"}, \"marks\": {\"type\": \"integer\"}}}}}}}},\n",
            "    \"flashcards\": {\"enabled\": \"generate_flashcards\", \"file\": \"flashcards.json\", \"target_calc\": lambda n: max(1, 25//n), \"target_msg\": \"Generate exactly {T} flashcards.\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"front\", \"back\", \"difficulty\"], \"properties\": {\"front\": {\"type\": \"string\"}, \"back\": {\"type\": \"string\"}, \"difficulty\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"concept_relationships\": {\"enabled\": \"generate_concept_relationships\", \"file\": \"concept_relationships.json\", \"target_calc\": lambda n: max(1, 30//n), \"target_msg\": \"Generate exactly {T} concept relationships.\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"source\", \"target\", \"relationship\"], \"properties\": {\"source\": {\"type\": \"string\"}, \"target\": {\"type\": \"string\"}, \"relationship\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"image_captions\": {\"enabled\": \"generate_image_captions\", \"file\": \"image_captions.json\", \"target_calc\": lambda n: \"all\", \"target_msg\": \"Generate captions (50-150 words) for all figures in the source.\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"figure_id\", \"caption\", \"educational_explanation\"], \"properties\": {\"figure_id\": {\"type\": \"string\"}, \"caption\": {\"type\": \"string\"}, \"educational_explanation\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"investigations\": {\"enabled\": \"generate_investigations\", \"file\": \"investigations.json\", \"target_calc\": lambda n: max(1, 8//n), \"target_msg\": \"Generate exactly {T} investigations.\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"title\", \"objective\", \"materials\", \"procedure\", \"observations\", \"conclusion\"], \"properties\": {\"title\": {\"type\": \"string\"}, \"objective\": {\"type\": \"string\"}, \"materials\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"procedure\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"observations\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"conclusion\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"teacher_notes\": {\"enabled\": \"generate_teacher_notes\", \"file\": \"teacher_notes.json\", \"target_calc\": lambda n: 1, \"target_msg\": \"Generate exactly 1 set of teacher notes for this section.\", \"schema\": {\"type\": \"object\", \"required\": [\"section\", \"teaching_tips\", \"common_errors\", \"discussion_questions\"], \"properties\": {\"section\": {\"type\": \"string\"}, \"teaching_tips\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"common_errors\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"discussion_questions\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}}},\n",
            "    \"prerequisites\": {\"enabled\": \"generate_prerequisites\", \"file\": \"prerequisites.json\", \"target_calc\": lambda n: max(1, 10//n), \"target_msg\": \"Generate exactly {T} prerequisites.\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"concept\", \"required_before\", \"reason\"], \"properties\": {\"concept\": {\"type\": \"string\"}, \"required_before\": {\"type\": \"boolean\"}, \"reason\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"difficulty_analysis\": {\"enabled\": \"generate_difficulty_analysis\", \"file\": \"difficulty_analysis.json\", \"target_calc\": lambda n: 1, \"target_msg\": \"Generate exactly 1 difficulty analysis profile.\", \"schema\": {\"type\": \"object\", \"required\": [\"easy_concepts\", \"medium_concepts\", \"hard_concepts\", \"estimated_learning_time_minutes\"], \"properties\": {\"easy_concepts\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"medium_concepts\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"hard_concepts\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"estimated_learning_time_minutes\": {\"type\": \"integer\"}}}},\n",
            "    \"faqs\": {\"enabled\": \"generate_faqs\", \"file\": \"faqs.json\", \"target_calc\": lambda n: max(1, 15//n), \"target_msg\": \"Generate exactly {T} FAQs.\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"question\", \"answer\"], \"properties\": {\"question\": {\"type\": \"string\"}, \"answer\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"common_doubts\": {\"enabled\": \"generate_common_doubts\", \"file\": \"common_doubts.json\", \"target_calc\": lambda n: max(1, 15//n), \"target_msg\": \"Generate exactly {T} common doubts with follow-up questions.\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"doubt\", \"explanation\", \"follow_up_questions\"], \"properties\": {\"doubt\": {\"type\": \"string\"}, \"explanation\": {\"type\": \"string\"}, \"follow_up_questions\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}}}}},\n",
            "    \"exam_questions\": {\"enabled\": \"generate_exam_questions\", \"file\": \"exam_questions.json\", \"target_calc\": lambda n: max(1, 20//n), \"target_msg\": \"Generate exactly {T} exam questions (mix of MCQ, Short Answer, Long Answer, HOTS/Application).\", \"schema\": {\"type\": \"object\", \"required\": [\"items\"], \"properties\": {\"items\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"question\", \"type\", \"answer\", \"marks\"], \"properties\": {\"question\": {\"type\": \"string\"}, \"type\": {\"type\": \"string\", \"enum\": [\"MCQ\", \"Short Answer\", \"Long Answer\", \"HOTS/Application\"]}, \"answer\": {\"type\": \"string\"}, \"marks\": {\"type\": \"integer\"}}}}}}}}\n",
            "}\n",
            "\n",
            "def strip_markdown_fences(text: str) -> str:\n",
            "    text = (text or \"\").strip()\n",
            "    if text.startswith(\"```\"):\n",
            "        text = re.sub(r\"^```[a-zA-Z0-9_-]*\\s*\", \"\", text).strip()\n",
            "        text = re.sub(r\"\\s*```$\", \"\", text).strip()\n",
            "    return text\n",
            "\n",
            "def extract_balanced_json_candidates(text: str) -> List[str]:\n",
            "    text = strip_markdown_fences(text)\n",
            "    candidates: List[str] = []\n",
            "    pairs = {\"{\": \"}\", \"[\": \"]\"}\n",
            "    for start, char in enumerate(text):\n",
            "        if char not in pairs:\n",
            "            continue\n",
            "        expected_stack = [pairs[char]]\n",
            "        in_string = False\n",
            "        escaped = False\n",
            "        for index in range(start + 1, len(text)):\n",
            "            current = text[index]\n",
            "            if escaped:\n",
            "                escaped = False\n",
            "                continue\n",
            "            if current == \"\\\\\":\n",
            "                escaped = True\n",
            "                continue\n",
            "            if current == '\\\"':\n",
            "                in_string = not in_string\n",
            "                continue\n",
            "            if in_string:\n",
            "                continue\n",
            "            if current in pairs:\n",
            "                expected_stack.append(pairs[current])\n",
            "            elif expected_stack and current == expected_stack[-1]:\n",
            "                expected_stack.pop()\n",
            "                if not expected_stack:\n",
            "                    candidates.append(text[start : index + 1])\n",
            "                    break\n",
            "    return candidates\n",
            "\n",
            "def extract_json_object(text: str) -> Any:\n",
            "    text = strip_markdown_fences(text)\n",
            "    decoder = json.JSONDecoder()\n",
            "    for candidate in [text, *extract_balanced_json_candidates(text)]:\n",
            "        candidate = candidate.strip()\n",
            "        if not candidate:\n",
            "            continue\n",
            "        try:\n",
            "            parsed, _ = decoder.raw_decode(candidate)\n",
            "            return parsed\n",
            "        except json.JSONDecodeError:\n",
            "            pass\n",
            "    raise ValueError(\"No JSON object found\")\n",
            "\n",
            "def schema_default(schema: Dict[str, Any]) -> Any:\n",
            "    schema_type = schema.get(\"type\")\n",
            "    if schema_type == \"object\":\n",
            "        result: Dict[str, Any] = {}\n",
            "        properties = schema.get(\"properties\", {})\n",
            "        for key in schema.get(\"required\", []):\n",
            "            result[key] = schema_default(properties.get(key, {}))\n",
            "        return result\n",
            "    if schema_type == \"array\":\n",
            "        return []\n",
            "    if schema_type in (\"number\", \"integer\"):\n",
            "        return 0\n",
            "    if schema_type == \"boolean\":\n",
            "        return False\n",
            "    return \"\"\n",
            "\n",
            "def normalize_payload_for_schema(payload: Any, schema: Dict[str, Any]) -> Dict[str, Any]:\n",
            "    if isinstance(payload, list) and schema.get(\"type\") == \"object\" and \"items\" in schema.get(\"properties\", {}):\n",
            "        payload = {\"items\": payload}\n",
            "    if not isinstance(payload, dict):\n",
            "        payload = schema_default(schema)\n",
            "    properties = schema.get(\"properties\", {})\n",
            "    for key in schema.get(\"required\", []):\n",
            "        if key not in payload or payload[key] is None:\n",
            "            payload[key] = schema_default(properties.get(key, {}))\n",
            "    return payload\n"
        ]
    })

    # 06_GENERATION LOGIC
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def enriched_section_text(section: SectionData) -> str:\n",
            "    parts = [f\"Section Title: {section.title}\", section.content]\n",
            "    if section.equations:\n",
            "        parts.append(\"Equations:\\n\" + \"\\n\".join(section.equations[:20]))\n",
            "    if section.tables:\n",
            "        table_lines = [json.dumps(t, ensure_ascii=False)[:2500] for t in section.tables[:5]]\n",
            "        parts.append(\"Tables:\\n\" + \"\\n\".join(table_lines))\n",
            "    captions = [f\"{fig.figure_id}: {fig.caption} (Image Path: {fig.image_path})\" for fig in section.figures]\n",
            "    if captions:\n",
            "        parts.append(\"Figure references:\\n\" + \"\\n\".join(captions[:20]))\n",
            "    return \"\\n\\n\".join(part for part in parts if part).strip()\n",
            "\n",
            "def prompt_for_artifact(section: SectionData, artifact_name: str, spec: Dict[str, Any], num_sections: int) -> str:\n",
            "    source_text = enriched_section_text(section)[:12000]\n",
            "    target_val = spec['target_calc'](num_sections)\n",
            "    target_instruction = spec['target_msg'].replace(\"{T}\", str(target_val))\n",
            "    schema = spec['schema']\n",
            "    \n",
            "    return f\"\"\"\\\n",
            "You are generating curriculum artifacts for offline school tutoring.\n",
            "Use only the Docling-extracted source section, including tables, equations, and figure captions.\n",
            "Do not invent facts.\n",
            "\n",
            "CRITICAL INSTRUCTIONS:\n",
            "- {target_instruction}\n",
            "- Return exactly ONE valid JSON object.\n",
            "- The first character must be {{ and the last character must be }}.\n",
            "- Do not use markdown fences. Do not include explanations before or after JSON.\n",
            "- Ensure the JSON strictly matches the Required JSON Schema.\n",
            "\n",
            "Artifact: {artifact_name}\n",
            "Required JSON Schema: {json.dumps(schema, ensure_ascii=False)}\n",
            "\n",
            "Source:\n",
            "{source_text}\n",
            "\"\"\"\n",
            "\n",
            "def generate_json(section: SectionData, artifact_name: str, spec: dict, num_sections: int) -> Dict[str, Any]:\n",
            "    digest = hashlib.sha256((section.section_id + artifact_name + section.content).encode(\"utf-8\")).hexdigest()\n",
            "    cpath = CACHE_ROOT / f\"{digest}.json\"\n",
            "    \n",
            "    if CONFIG[\"resume\"] and cpath.exists():\n",
            "        return json.loads(cpath.read_text(encoding=\"utf-8\"))\n",
            "\n",
            "    schema = spec['schema']\n",
            "    base_prompt = prompt_for_artifact(section, artifact_name, spec, num_sections)\n",
            "    last_error = \"\"\n",
            "    max_retries = max(1, int(CONFIG[\"max_retries\"]))\n",
            "    \n",
            "    for retry in range(max_retries):\n",
            "        prompt = base_prompt if retry == 0 else base_prompt + f\"\\n\\nYour previous response was invalid because: {last_error}\\nReturn corrected JSON only.\"\n",
            "        result = CONTENT_LLM(prompt, max_tokens=CONFIG[\"max_tokens\"], temperature=CONFIG[\"temperature\"], top_p=CONFIG[\"top_p\"])\n",
            "        raw = result[\"choices\"][0][\"text\"]\n",
            "        try:\n",
            "            parsed = normalize_payload_for_schema(extract_json_object(raw), schema)\n",
            "            jsonschema_validate(parsed, schema)\n",
            "            cpath.write_text(json.dumps(parsed, indent=2, ensure_ascii=False), encoding=\"utf-8\")\n",
            "            return parsed\n",
            "        except Exception as exc:\n",
            "            last_error = str(exc)\n",
            "    \n",
            "    payload = normalize_payload_for_schema(schema_default(schema), schema)\n",
            "    payload[\"_generation_failed\"] = True\n",
            "    payload[\"_failure_reason\"] = last_error\n",
            "    cpath.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding=\"utf-8\")\n",
            "    return payload\n",
            "\n",
            "all_artifacts = {}\n",
            "VALIDATION_REPORT = {\"total_sections\": 0, \"successful_artifacts\": {}, \"failed_artifacts\": {}, \"errors\": []}\n",
            "start_time = time.time()\n",
            "\n",
            "for chapter in tqdm(CHAPTERS, desc=\"Chapters\"):\n",
            "    num_sections = max(1, len(chapter.sections))\n",
            "    for section in tqdm(chapter.sections, desc=f\"Sections: {chapter.chapter_title}\", leave=False):\n",
            "        VALIDATION_REPORT[\"total_sections\"] += 1\n",
            "        for artifact_name, spec in ARTIFACT_SPECS.items():\n",
            "            if CONFIG.get(spec[\"enabled\"], False):\n",
            "                payload = generate_json(section, artifact_name, spec, num_sections)\n",
            "                all_artifacts.setdefault(artifact_name, []).append({\"section_id\": section.section_id, \"chapter_id\": chapter.document_id, \"payload\": payload})\n",
            "                if payload.get(\"_generation_failed\"):\n",
            "                    VALIDATION_REPORT[\"failed_artifacts\"][artifact_name] = VALIDATION_REPORT[\"failed_artifacts\"].get(artifact_name, 0) + 1\n",
            "                    VALIDATION_REPORT[\"errors\"].append({\"section_id\": section.section_id, \"artifact\": artifact_name, \"error\": payload.get(\"_failure_reason\")})\n",
            "                else:\n",
            "                    VALIDATION_REPORT[\"successful_artifacts\"][artifact_name] = VALIDATION_REPORT[\"successful_artifacts\"].get(artifact_name, 0) + 1\n",
            "\n",
            "for artifact_name, spec in ARTIFACT_SPECS.items():\n",
            "    if CONFIG.get(spec[\"enabled\"], False):\n",
            "        output_file = PACK_ROOT / spec[\"file\"]\n",
            "        output_file.write_text(json.dumps(all_artifacts.get(artifact_name, []), indent=2, ensure_ascii=False), encoding=\"utf-8\")\n",
            "\n",
            "VALIDATION_REPORT[\"total_time_seconds\"] = round(time.time() - start_time, 2)\n",
            "(PACK_ROOT / \"generation_report.json\").write_text(json.dumps(VALIDATION_REPORT, indent=2), encoding=\"utf-8\")\n",
            "print(\"LLM JSON Generation complete. Validation report saved.\")\n"
        ]
    })

    # 07_FINAL_ZIP
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "zip_path = OUTPUT_ROOT / CONFIG[\"artifact_zip_name\"]\n",
            "with zipfile.ZipFile(zip_path, \"w\", zipfile.ZIP_DEFLATED) as archive:\n",
            "    for file_path in PACK_ROOT.rglob(\"*.json\"):\n",
            "        archive.write(file_path, arcname=str(file_path.relative_to(PACK_ROOT.parent)))\n",
            "print(\"Process complete. Final zip saved to\", zip_path)\n"
        ]
    })
    
    with open('/home/akash/Desktop/PIHUB/02_ARTIFACT_GENERATION.ipynb', 'w') as f:
        json.dump({"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}, f, indent=2)

build_02()
